### PR TITLE
Update to Nuxt 2.14

### PR DESCRIPTION
**Pull request by samlfair**
Upgraded dependencies, html serializer, link handling.

### CODE REVIEW

**Comment by phillysnow** [comment]
@samlfair I just tested this and previews/releases seem to be failing. Can you test this on your side with the repo I just invited you to?

**Comment by samlfair** [comment]
@phillysnow Yeah, the previews are failing for me with that repo. I found your comment about Toolbar V1 vs V2, so I duplicated the repo as `multi-language-example-sam`, and the preview seems to be working. I'll send you an invite to my repo so you can test it out.

However, these two fields don't seem to exist in the custom types, so they're breaking the page for me:

https://github.com/prismicio/nuxt-multi-language-site/blob/50e508c87f6fabe9bff54e2ef752145e03ba73cf/components/slices/InfoWithImage.vue#L19

https://github.com/prismicio/nuxt-multi-language-site/blob/50e508c87f6fabe9bff54e2ef752145e03ba73cf/components/slices/TextInfo.vue#L4

I'm not sure why it works in your repo but not in mine — I don't see those fields in your repo either. Is it okay if I remove them and commit?

**Comment by phillysnow** [comment]
@samlfair OK, I see what you mean. I finally got time for this, yeah it's strange that this didn't cause issues before. You can go ahead and removed them and commit like you said. Then we're good to go.

**Comment by samlfair** [comment]
@phillysnow Cool I removed those icons, so this should be good to merge.

**Pull request merged**
